---
name: "Tests release PRs"

on:
  pull_request:
    types:
      - release

jobs:
  pass-all-tests:
    if: github.repository == 'artem-experiments/gh-actions-release' && startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Go-go-go, procced with your release! ;-)'
