---
name: "Tests release PRs"

on:
  pull_request:
    branches:
      - release/v*

jobs:
  pass-all-tests:
    if: github.repository == 'artem-experiments/gh-actions-release'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Go-go-go, procced with your release! ;-)'
          cat $GITHUB_EVENT_PATH
          echo '${{ github.ref_name }}'
