---
name: "Tests release PRs"

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.head_ref }}
          echo BLA
          echo ${{ github.event.pull_request.head.ref }}
  pass-all-tests:
    if: github.repository == 'artem-experiments/gh-actions-release' && startsWith('release/v', github.head_ref)
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Go-go-go, procced with your release! ;-)'
          cat $GITHUB_EVENT_PATH
          echo '${{ github.ref_name }}'
