---
name: "Tests release PRs"

on:
  pull_request:
    branches:
      - 'release/v*'

jobs:
  pass-all-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Go-go-go, procced with your release! ;-)'
